DBSettings:
  dbUser: postgres
  dbPassword: postgres
  dbHost: localhost
  dbPort: 5432
  dbName: postgres

ProgramSettings:
  bindAddress: 127.0.0.1
  port: 8080
  jiraUrl: https://issues.apache.org/jira/rest/api/2/
  threadCount: 5
  issueInOneRequest: 75
  maxTimeSleep: 300ms
  minTimeSleep: 10ms